# Generated by Django 4.2.5 on 2023-10-08 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmapp', '0007_productavailability_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAvailability',
            new_name='ProductAvailability1',
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfile1',
        ),
    ]
