# Generated by Django 4.2.5 on 2023-10-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0009_rename_productavailability1_productavailability_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAvailability',
        ),
    ]
