# Generated by Django 4.2.5 on 2023-10-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0010_delete_productavailability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
