# Generated by Django 4.2.5 on 2023-10-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0014_delete_productavailability_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
